# Generated by Django 3.1.1 on 2023-01-25 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('ano_nascimento', models.IntegerField()),
                ('cpf', models.CharField(max_length=14)),
                ('cidade', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('rua', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('disciplina_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina')),
            ],
        ),
    ]
